version: '3.1'

services:
  db:
    image: postgres:10.17-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=postgres"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:


